- alias: "Vicky Leave Mom"
  trigger:
    - platform: zone
      event: leave
      zone: zone.vicky_mom
      entity_id: device_tracker.life360_vicky_conner
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker,media_player.living_room_2,media_player.office
        volume: 0.3
        message: 'Vicky has left Vicky Mom'
        delay: '00:00:05'

- alias: "Vicky Arrived 75 and Man O War"
  trigger:
    - platform: zone
      event: enter
      zone: zone.75_man_o_war
      entity_id: device_tracker.life360_vicky_conner
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker,media_player.living_room_2,media_player.office
        volume: 0.4
        message: 'Vicky has arrived at 75 and Man O War'
        delay: '00:00:05'

- alias: "Vicky Arrived Todds Road and Man O War"
  trigger:
    - platform: zone
      event: enter
      zone: zone.todds_road_man_o_war
      entity_id: device_tracker.life360_vicky_conner
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker,media_player.living_room_2,media_player.office
        volume: 0.4
        message: 'Vicky has arrived at Todds Road and Man O War'
        delay: '00:00:05'

- alias: "Vicky Arrived Richmond Road and Man O War"
  trigger:
    - platform: zone
      event: enter
      zone: zone.richmond_road_man_o_war
      entity_id: device_tracker.life360_vicky_conner
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker,media_player.living_room_2,media_player.office
        volume: 0.4
        message: 'Vicky has arrived at Richmond Road and Man O War'
        delay: '00:00:05'

- alias: "Vicky Leave Garden Springs"
  trigger:
    - platform: zone
      event: leave
      zone: zone.garden_springs_elementary
      entity_id: device_tracker.life360_vicky_conner
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker,media_player.living_room_2,media_player.office
        volume: 0.4
        message: 'Vicky has left Vicky Work'
        delay: '00:00:05'

- alias: "Vicky Arrived at Home Radius"
  trigger:
    - platform: zone
      event: enter
      zone: zone.home_radius
      entity_id: device_tracker.life360_vicky_conner
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker,media_player.living_room_2,media_player.office
        volume: 0.4
        message: 'Vicky has arrived at Home Radius Opening Garage Door'
        delay: '00:00:05'

- alias: "Chris or Vicky Arrived Home Opening Garage Door"
  trigger:
    - platform: zone
      event: enter
      zone: zone.home_radius
      entity_id: device_tracker.life360_vicky_conner
    - platform: zone
      event: enter
      zone: zone.home_radius
      entity_id: device_tracker.life360_chris_conner
  action:
    - service_template: >
        {%- if is_state("cover.garage_mqtt", "closed") -%}
          cover.open_cover
        {% endif %}
      entity_id: cover.garage_mqtt


- alias: "Vicky Left at Home Radius"
  trigger:
    - platform: zone
      event: enter
      zone: zone.home_radius
      entity_id: device_tracker.life360_vicky_conner
  action:
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker,media_player.living_room_2,media_player.office
        volume: 0.4
        message: 'Vicky has left Home Radius Closing Garage Door'
        delay: '00:00:05'

- alias: "Chris or Vicky Left Home Closing Garage Door"
  trigger:
    - platform: zone
      event: leave
      zone: zone.home_radius
      entity_id: device_tracker.life360_vicky_conner
    - platform: zone
      event: leave
      zone: zone.home_radius
      entity_id: device_tracker.life360_chris_conner
  action:
    - service_template: >
        {%- if is_state("cover.garage_mqtt", "open") -%}
          cover.close_cover
        {% endif %}
      entity_id: cover.garage_mqtt

- alias: 'Notify and Close if garage is open for 5 mins'
  trigger:
    platform: state
    entity_id:
      - cover.garage_mqtt
    from: closed
    to: open
    for:
      minutes: 1
  action:
    - service_template: >
        {%- if is_state("cover.garage_mqtt", "open") -%}
          cover.close_cover
        {% endif %}
      entity_id: cover.garage_mqtt
    - service: script.sonos_say
      data_template:
        sonos_entity: media_player.bedroom_speaker,media_player.living_room_2,media_player.office
        volume: 0.4
        message: 'The garage door has been open for 1 minute.  Closing garage door'
        delay: '00:00:05'


#- alias: "Chris Arrived Home Opening Garage Door"
#  trigger:
#    - platform: zone
#      event: enter
#      zone: zone.home_radius
#      entity_id: device_tracker.life360_chris_conner
#  action:
#    - service: cover.open_cover
#      data_template:
#        entity_id: cover.garage_mqtt

#- alias: "Chris Left Home Closing Garage Door"
#  trigger:
#    - platform: zone
#      event: leave
#      zone: zone.home_radius
#      entity_id: device_tracker.life360_chris_conner
#  action:
#    - service: cover.close_cover
#      data_template:
#        entity_id: cover.garage_mqtt

- alias: "Sync W Bridge On Start"
  trigger:
    - platform: homeassistant
      # Event can also be 'shutdown'
      event: start
  action:
    - service: ha_mqtt_bridge_sync.sync

- alias: Restart on Error Upstairs Vacuum
  action:
    - service: vacuum.start_pause
      entity_id:
      - vacuum.upstairs_vacuum
  condition: []
  id: '1517181580468'
  trigger:
    - platform: template
      value_template: '{% if is_state_attr(''vacuum.upstairs_vacuum'', ''error'', ''Clean
        main brush'') %}true{% endif %}'

- alias: 'test'
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.office
        volume: 0.5
        message: 'Vicky is up stairs!'
        delay: '00:00:05'


- alias: Life360 Overdue Update
  trigger:
    platform: event
    event_type: device_tracker.life360_update_overdue
  action:
    service: notify.email_me
    data_template:
      title: Life360 update overdue
      message: >
        Update for {{
          state_attr(trigger.event.data.entity_id, 'friendly_name') or
          trigger.event.data.entity_id
        }} is overdue.

- alias: Life360 Update Restored
  trigger:
    platform: event
    event_type: device_tracker.life360_update_restored
  action:
    service: notify.email_me
    data_template:
      title: Life360 update restored
      message: >
        Update for {{
          state_attr(trigger.event.data.entity_id, 'friendly_name') or
          trigger.event.data.entity_id
        }} restored after {{ trigger.event.data.wait }}.



#- action:
#  - service: vacuum.turn_on
#    entity_id:
#    - vacuum.upstairs_vacuum
#  alias: Start Upstairs Vacuum
#  condition: []
#  id: '1516677830561'
#  trigger:
#  - payload: 'on'
#    platform: mqtt
#    topic: smartthings/Upstairs Vacuum/switch/state
#- action:
#  - service: vacuum.return_to_base
#    entity_id: vacuum.upstairs_vacuum
#  alias: Return Home Upstairs Vacuum
#  condition: []
#  id: '1516677830561'
#  trigger:
#  - payload: 'off'
#    platform: mqtt
#    topic: smartthings/Upstairs Vacuum/switch/state
- action:
  - service: vacuum.start_pause
    entity_id:
    - vacuum.upstairs_vacuum
  alias: Restart on Error Upstairs Vacuum
  condition: []
  id: '1517181580468'
  trigger:
  - platform: template
    value_template: '{% if is_state_attr(''vacuum.upstairs_vacuum'', ''error'', ''Clean
      main brush'') %}true{% endif %}'
#- action:
#  - service: vacuum.turn_on
#    entity_id:
#    - vacuum.downstairs_vacuum
#  alias: Start Downstairs Vacuum
#  condition: []
#  id: '1516677830561'
#  trigger:
#  - payload: 'on'
#    platform: mqtt
#    topic: smartthings/Downstairs Vacuum/switch/state
#- action:
#  - service: vacuum.return_to_base
#    entity_id:
#    - vacuum.downstairs_vacuum
#  alias: Return Home Downstairs Vacuum
#  condition: []
#  id: '1516677830561'
#  trigger:
#  - payload: 'off'
#    platform: mqtt
#    topic: smartthings/Downstairs Vacuum/switch/state
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.battery_level }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/battery
#    service: mqtt.publish
#  alias: Upstairs Vacuum Battery to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.status }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/status
#    service: mqtt.publish
#  alias: Upstairs Vacuum Status to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.fan_speed }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/fan_speed
#    service: mqtt.publish
#  alias: Upstairs Vacuum Fan Speed to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.fan_speed_list }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/fan_speed_list
#    service: mqtt.publish
#  alias: Upstairs Vacuum Fan Speed List to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.device_state_attributes }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/device_state_attributes
#    service: mqtt.publish
#  alias: Upstairs Vacuum Device State Attributes List to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.is_on }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/is_on
#    service: mqtt.publish
#  alias: Upstairs Vacuum Is On to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.available }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/available
#    service: mqtt.publish
#  alias: Upstairs Vacuum Available to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.supported_features }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/supported_features
#    service: mqtt.publish
#  alias: Upstairs Vacuum Supported Features to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.upstairs_vacuum.attributes.error }}'
#      retain: 'true'
#      topic: smartthings/Upstairs Vacuum/homeassistant/error
#    service: mqtt.publish
#  alias: Upstairs Vacuum Error to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.battery_level }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/battery
#    service: mqtt.publish
#  alias: Downstairs Vacuum Battery to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.status }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/status
#    service: mqtt.publish
#  alias: Downstairs Vacuum Status to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.fan_speed }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/fan_speed
#    service: mqtt.publish
#  alias: Downstairs Vacuum Fan Speed to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.fan_speed_list }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/fan_speed_list
#    service: mqtt.publish
#  alias: Downstairs Vacuum Fan Speed List to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.device_state_attributes }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/device_state_attributes
#    service: mqtt.publish
#  alias: Downstairs Vacuum Device State Attributes List to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.is_on }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/is_on
#    service: mqtt.publish
#  alias: Downstairs Vacuum Is On to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.available }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/available
#    service: mqtt.publish
#  alias: Downstairs Vacuum Available to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.supported_features }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/supported_features
#    service: mqtt.publish
#  alias: Downstairs Vacuum Supported Features to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
#- action:
#  - data_template:
#      payload_template: '{{ states.vacuum.downstairs_vacuum.attributes.error }}'
#      retain: 'true'
#      topic: smartthings/Downstairs Vacuum/homeassistant/error
#    service: mqtt.publish
#  alias: Downstairs Vacuum Error to SmartThings
#  condition: []
#  id: '1517606448000'
#  trigger:
#    platform: time
#    seconds: '/5'
