homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 306
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml


# Text to speech
tts:
  - platform: google
#  - platform: voicerss

alexa:

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

#ifttt:
#  key: REDACTED

ffmpeg:

#python_script:
#
#################################################################
## Includes
#################################################################

automation: !include automations.yaml
#automation: !include_dir_merge_list automation
#recorder: !include recorder.yaml
#logbook: !include logbook.yaml
logger: !include logger.yaml
history: !include history.yaml
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
light: !include_dir_list lights/
switch: !include_dir_list switches/
#input_boolean: !include input_boolean.yaml
#input_select: !include input_select.yaml
script: !include scripts.yaml
#weblink: !include weblinks.yaml
intent_script: !include intent_script.yaml
http: !include http.yaml
media_player: !include media_player.yaml
#sonos: !include sonos.yaml #NOT USED FOUND IN MEDIA_PLAYER
vacuum: !include vacuum.yaml
cover: !include cover.yaml
mqtt: !include mqtt.yaml
ha_mqtt_bridge_sync: !include ha_mqtt_bridge_sync.yaml
sonoff_garage_sync: !include sonoff_garage_sync.yaml
nest: !include nest.yaml
apple_tv: !include apple_tv.yaml
remote: !include remote.yaml
#panel_iframe: !include panel_iframe.yaml
device_tracker: !include device_tracker.yaml

