version: '2'
services:
  homeassistant:
    container_name: docker-homeassistant
    image: homeassistant/home-assistant
    volumes:
      - /opt/smarthome/home-assistant-config:/config
      - /etc/localtime:/etc/localtime:ro
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
