name: Conners Name
title: Conners Title
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/bignumber-card.js?v=0.0.1
    type: js
  - url: /local/monster-card.js?v=0.0.1
    type: js
  - url: /local/gauge-card.js?v=0.0.1
    type: js
#  - url: /local/last-motion-card.js?v=0.0.1
#    type: js
#  - url: /local/card-tracker.js?v=0.0.1
#    type: js
#  - url: /local/useful-markdown-card.js?v=0.0.1
#    type: js
  
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
#excluded_entities:
#  - weblink.router
views:
  - icon: mdi:home
    title: Home
    id: home
    cards:
#      - type: entity-filter
#        entities:
#          - device_tracker.life360_chris_conner
#          - device_tracker.life360_vicky_conner
#        state_filter:
#          - 'home'
#        card:
#          type: glance
#          title: People that are home

      - type: entities
        title: Family
        entities:
          - device_tracker.life360_chris_conner
          - device_tracker.life360_vicky_conner

      - type: picture-glance
        title: Front Door
        image:
        camera_image: camera.front_door
        entities:
          - camera.front_door
          - binary_sensor.front_door_camera_person_detected
          - binary_sensor.motion_front_door
          - light.entry_light
          - binary_sensor.front_door_camera_sound_detected

      - type: picture-glance
        title: Living Room
        image:
        camera_image: camera.living_room
        entities:
          - camera.living_room
          - binary_sensor.living_room_camera_motion_detected
          - binary_sensor.living_room_camera_sound_detected
          - group.living_room_lights
  #        - switch.living_room_scentsy_relay

      - type: picture-glance
        title: Garage
        image:
        camera_image: camera.garage
        entities:
          - camera.garage
          - binary_sensor.garage_camera_motion_detected
          - binary_sensor.garage_camera_sound_detected
          - cover.garage_mqtt

      - type: entities
        title: Garage
        entities:
          - cover.garage_mqtt
  
      - type: entities
        title: Downstairs Thermostat
        show_header_toggle: true
        entities:
#          - binary_sensor.home_away
          - binary_sensor.downstairs_thermostat_fan
          - binary_sensor.downstairs_thermostat_has_leaf
          - binary_sensor.downstairs_thermostat_is_locked
          - binary_sensor.downstairs_thermostat_is_using_emergency_heat
          - binary_sensor.downstairs_thermostat_online
          - sensor.downstairs_thermostat_humidity
          - sensor.downstairs_thermostat_hvac_state
          - sensor.downstairs_thermostat_operation_mode
          - sensor.downstairs_thermostat_target
          - sensor.downstairs_thermostat_temperature
          - climate.downstairs_thermostat

#      - type: entities
#        title: Downstairs Thermostat Set
#        show_header_toggle: true
#        entities:
#          - climate.downstairs_thermostat
  
      - type: glance
        title: Downstairs Vacuum
        entities:
          - entity: vacuum.downstairs_vacuum
            name: Locate
            icon: mdi:bell-ring
            tap_action: call-service
            service: vacuum.locate
  
          - entity: vacuum.downstairs_vacuum
            name: Go Home
            tap_action: call-service
            icon: mdi:home
            service: vacuum.return_to_base
  
          - entity: vacuum.downstairs_vacuum
            name: Go
            icon: mdi:play-pause
            tap_action: call-service
            service: vacuum.start_pause

          - entity: vacuum.downstairs_vacuum
            name: Pause
            icon: mdi:play-pause
            tap_action: call-service
            service: vacuum.start_pause

          - entity: vacuum.downstairs_vacuum
            name: Stop
            icon: mdi:stop
            tap_action: call-service
            service: vacuum.stop

          - entity: sensor.downstairs_vacuum_status
            name: Status
  
          - entity: sensor.downstairs_vacuum_battery
            name: Battery

  - icon: mdi:pot-mix
    title: Kitchen
    id: kitchen
    cards: 
      - type: picture-glance
        title: Kitchen
        image:
        camera_image: camera.office
        entities:
          - camera.office
          - binary_sensor.office_camera_motion_detected
          - input_select.dishwasher_status
          - climate.kitchen

      - type: picture-glance
        title: Front Door
        image:
        camera_image: camera.front_door
        entities:
          - camera.front_door
          - binary_sensor.front_door_camera_person_detected
          - binary_sensor.motion_front_door
          - light.entry_light
          - binary_sensor.front_door_camera_sound_detected
  
      - type: entities
        title: Lights
        entities:
          - light.kitchen_bar_light
          - light.kitchen_cabinet_led
          - light.kitchen_cabinet_light
          - light.kitchen_dish_light
          - light.kitchen_light
          - light.kitchen_refrigerator_light
          - light.kitchen_sink_light
          - light.nook_light
  
  - icon: mdi:bed-empty
    title: Bedroom
    id: bedroom
    cards: 
      - type: picture-glance
        title: Front Door
        image:
        camera_image: camera.front_door
        entities:
          - camera.front_door
          - binary_sensor.front_door_camera_person_detected
          - binary_sensor.motion_front_door
          - light.entry_light
          - binary_sensor.front_door_camera_sound_detected
  
      - type: entities
        title: Lights
        entities:
          - light.bedroom_light
          - light.master_bathroom_closet
          - light.master_bathroom_light_one
          - light.master_bathroom_light_three
          - light.master_bathroom_light_two
          - light.master_bathroom_shower
          - light.master_bathroom_toilet
          - light.master_bathroom_tub
  
      - type: picture-glance
        title: Garage
        image:
        camera_image: camera.garage
        entities:
          - camera.garage
          - binary_sensor.garage_camera_motion_detected
          - binary_sensor.garage_camera_sound_detected
          - cover.garage_mqtt

      - type: entities
        title: Garage
        entities:
          - cover.garage_mqtt
 
      - type: entities
        title: Upstairs Thermostat
        show_header_toggle: true
        entities:
#          - binary_sensor.home_away
          - binary_sensor.upstairs_thermostat_fan
          - binary_sensor.upstairs_thermostat_has_leaf
          - binary_sensor.upstairs_thermostat_is_locked
          - binary_sensor.upstairs_thermostat_is_using_emergency_heat
          - binary_sensor.upstairs_thermostat_online
          - sensor.upstairs_thermostat_humidity
          - sensor.upstairs_thermostat_hvac_state
          - sensor.upstairs_thermostat_operation_mode
          - sensor.upstairs_thermostat_target
          - sensor.upstairs_thermostat_temperature
          - climate.upstairs_thermostat 

      - type: glance
        title: Upstairs Vacuum
        entities:
          - entity: vacuum.upstairs_vacuum
            name: Locate
            icon: mdi:bell-ring
            tap_action: call-service
            service: vacuum.locate

          - entity: vacuum.upstairs_vacuum
            name: Go Home
            tap_action: call-service
            icon: mdi:home
            service: vacuum.return_to_base

          - entity: vacuum.upstairs_vacuum
            name: Go
            icon: mdi:play-pause
            tap_action: call-service
            service: vacuum.start_pause

          - entity: vacuum.upstairs_vacuum
            name: Pause
            icon: mdi:play-pause
            tap_action: call-service
            service: vacuum.start_pause

          - entity: vacuum.upstairs_vacuum
            name: Stop
            icon: mdi:stop
            tap_action: call-service
            service: vacuum.stop

          - entity: sensor.upstairs_vacuum_status
            name: Status

          - entity: sensor.upstairs_vacuum_battery
            name: Battery


